version: '3'

services: 
    react-app:
        # for windows only
        environment:
            - CHOKIDAR_USEPOLLING=true
        # interactive mode    
        stdin_open: true # docker run -i
        tty: true        # docker run -t    
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes: 
            - /app/node_modules
            - .:/app    

    # for running test with live reload
    tests:
        # for windows only
        environment:
            - CHOKIDAR_USEPOLLING=true
        # interactive mode    
        stdin_open: true # docker run -i
        tty: true        # docker run -t    
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - .:/app
        # over ride the starting command
        command: ["npm", "run", "test"]    
                