# setting super user permissions
sudo: required

services: 
  - docker

before_install:
  # this won't run, as won't resolve the alias ./frontend-app
  - docker build -t web-app -f Dockerfile.dev frontend-app

scripts:
  - docker run web-app npm run test -- --coverage

